### ISSUE TITLE
[Fresh Installation of OpenHAB3] Not populating Items list

### ISSUE THREAD

**Issue by MDAR** [jeroenhendricksen/node-red-contrib-openhab3#7]
2021 May 21st
Node set version - V1.3.5

Hi

I've tried setting up 3 different machines in the last 2 days with either DietPi or Ubuntu.
Node-RED 1.3.5
openHAB3

I have added an API to openHAB3 and this works really well with the CURL commands.

Apparently I have added it correctly to the openHAB controller node because I have been able to edit the JSON files to address the correct Items .

However, the dropdown for the Items just doesn't get populated within any of the openHAB3 nodes, it just remains blank, like this

![image](https://user-images.githubusercontent.com/10905891/119171242-39897780-ba5c-11eb-9ed3-2cc702dfb4c2.png)

I had to edit the JSON for each In and Out node to get the following flow to work.

You are very welcome to remotely connect to the machine and see what is happening, as it is only connected to a demo unit.

```
[
    {
        "id": "5604c6aa.1aabd8",
        "type": "tab",
        "label": "Exec Commands",
        "disabled": false,
        "info": ""
    },
    {
        "id": "9e7962e1.14d0a",
        "type": "inject",
        "z": "5604c6aa.1aabd8",
        "name": "Any trigger & 05:00",
        "repeat": "",
        "crontab": "00 05 * * *",
        "once": false,
        "onceDelay": 0.1,
        "topic": "",
        "payload": "",
        "payloadType": "date",
        "x": 920,
        "y": 40,
        "wires": [
            [
                "d34d5904.4c1318"
            ]
        ]
    },
    {
        "id": "d34d5904.4c1318",
        "type": "exec",
        "z": "5604c6aa.1aabd8",
        "command": "sudo systemctl restart velserv",
        "addpay": false,
        "append": "",
        "useSpawn": "false",
        "timer": "",
        "oldrc": false,
        "name": "Restart Velserv",
        "x": 1290,
        "y": 100,
        "wires": [
            [
                "340cf435.66c52c",
                "ef0a8e18.fe027"
            ],
            [],
            []
        ]
    },
    {
        "id": "340cf435.66c52c",
        "type": "exec",
        "z": "5604c6aa.1aabd8",
        "command": "curl -X PUT --header \"Content-Type: application/json\" --header \"Accept: application/json\" -d \"FALSE\" \"http://oh.NodeRED.gjjqDn66jfnwGgd7SBv9COxZfgFvXezGeTzL4TEbns1DxRjkHkqsybjUApkYGWgmP4bTq5xAIJEjwlp2Ig@localhost:8080/rest/things/velbus%3Anetworkbridge%3AVelbusNetworkBridge/enable\"",
        "addpay": false,
        "append": "",
        "useSpawn": "false",
        "timer": "",
        "oldrc": false,
        "name": "Disable Velbus Bridge",
        "x": 1290,
        "y": 280,
        "wires": [
            [
                "b4a721fd.a12d2",
                "baa39aa9.b8b558"
            ],
            [],
            []
        ]
    },
    {
        "id": "7e011af5.a92b94",
        "type": "exec",
        "z": "5604c6aa.1aabd8",
        "command": "curl -X PUT --header \"Content-Type: application/json\" --header \"Accept: application/json\" -d \"TRUE\" \"http://oh.NodeRED.gjjqDn66jfnwGgd7SBv9COxZfgFvXezGeTzL4TEbns1DxRjkHkqsybjUApkYGWgmP4bTq5xAIJEjwlp2Ig@localhost:8080/rest/things/velbus%3Anetworkbridge%3AVelbusNetworkBridge/enable\"",
        "addpay": false,
        "append": "",
        "useSpawn": "false",
        "timer": "",
        "oldrc": false,
        "name": "Enable Velbus Bridge",
        "x": 1690,
        "y": 280,
        "wires": [
            [
                "2625872e.939748",
                "41be273b.b1aa48"
            ],
            [],
            []
        ]
    },
    {
        "id": "b4a721fd.a12d2",
        "type": "delay",
        "z": "5604c6aa.1aabd8",
        "name": "",
        "pauseType": "delay",
        "timeout": "5",
        "timeoutUnits": "seconds",
        "rate": "1",
        "nbRateUnits": "1",
        "rateUnits": "second",
        "randomFirst": "1",
        "randomLast": "5",
        "randomUnits": "seconds",
        "drop": false,
        "x": 1510,
        "y": 280,
        "wires": [
            [
                "7e011af5.a92b94"
            ]
        ]
    },
    {
        "id": "1eb69ba9.02d514",
        "type": "comment",
        "z": "5604c6aa.1aabd8",
        "name": "These two commands needs the last bits editing to suit your exact setup",
        "info": "curl -X PUT --header \"Content-Type: application/json\" --header \"Accept: application/json\" -d \"FALSE\" \"http://127.0.0.1:8080/rest/things/velbus%3Anetworkbridge%3Ad212bf44/enable\"\n\n\nWhere the section that currenly says \n\nvelbus%3Anetworkbridge%3Ad212bf44\n\nwould need to be have the last part changed to suit the Unique ID of you Velbus network bridge\n\nIf using the Text File Thing for Velbus bridge, it would simply read as\n\nvelbus%3networkbridge%3VelbusNetworkBridge\n\n\nmakig the whole command line either\n\ncurl -X PUT --header \"Content-Type: application/json\" --header \"Accept: application/json\" -d \"FALSE\" \"http://127.0.0.1:8080/rest/things/velbus%3networkbridge%3VelbusNetworkBridge/enable\"\nfor Disabled\n\nor\n\ncurl -X PUT --header \"Content-Type: application/json\" --header \"Accept: application/json\" -d \"TRUE\" \"http://127.0.0.1:8080/rest/things/velbus%3networkbridge%3VelbusNetworkBridge/enable\"\n\nfor enabled",
        "x": 1670,
        "y": 180,
        "wires": []
    },
    {
        "id": "6a474e01.41478",
        "type": "exec",
        "z": "5604c6aa.1aabd8",
        "command": "sudo reboot",
        "addpay": false,
        "append": "",
        "useSpawn": "true",
        "timer": "",
        "oldrc": false,
        "name": "",
        "x": 1270,
        "y": 440,
        "wires": [
            [],
            [],
            []
        ]
    },
    {
        "id": "9d5dc833.035108",
        "type": "inject",
        "z": "5604c6aa.1aabd8",
        "name": "",
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "",
        "payload": "Now",
        "payloadType": "str",
        "x": 920,
        "y": 420,
        "wires": [
            [
                "6a474e01.41478"
            ]
        ]
    },
    {
        "id": "d2f421e5.45228",
        "type": "exec",
        "z": "5604c6aa.1aabd8",
        "command": "sudo poweroff -h -n",
        "addpay": false,
        "append": "",
        "useSpawn": "true",
        "timer": "",
        "oldrc": false,
        "name": "",
        "x": 1280,
        "y": 880,
        "wires": [
            [],
            [],
            []
        ]
    },
    {
        "id": "ac5d0f87.6d794",
        "type": "inject",
        "z": "5604c6aa.1aabd8",
        "name": "",
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "",
        "payload": "Now",
        "payloadType": "str",
        "x": 910,
        "y": 860,
        "wires": [
            [
                "d2f421e5.45228"
            ]
        ]
    },
    {
        "id": "bd25f294.c0f82",
        "type": "ui_button",
        "z": "5604c6aa.1aabd8",
        "name": "",
        "group": "e9824075.26cba",
        "order": 6,
        "width": 0,
        "height": 0,
        "passthru": false,
        "label": "Reboot",
        "tooltip": "",
        "color": "",
        "bgcolor": "",
        "icon": "",
        "payload": "now",
        "payloadType": "str",
        "topic": "",
        "x": 960,
        "y": 480,
        "wires": [
            [
                "6a474e01.41478"
            ]
        ]
    },
    {
        "id": "868317f0.cd8ab8",
        "type": "ui_button",
        "z": "5604c6aa.1aabd8",
        "name": "",
        "group": "e9824075.26cba",
        "order": 7,
        "width": 0,
        "height": 0,
        "passthru": false,
        "label": "Poweroff",
        "tooltip": "",
        "color": "",
        "bgcolor": "",
        "icon": "",
        "payload": "now",
        "payloadType": "str",
        "topic": "",
        "x": 950,
        "y": 920,
        "wires": [
            [
                "d2f421e5.45228"
            ]
        ]
    },
    {
        "id": "de25758a.6fc028",
        "type": "ui_button",
        "z": "5604c6aa.1aabd8",
        "name": "",
        "group": "e9824075.26cba",
        "order": 2,
        "width": 0,
        "height": 0,
        "passthru": false,
        "label": "Restart Velserv",
        "tooltip": "",
        "color": "",
        "bgcolor": "{{colour}}",
        "icon": "",
        "payload": "now",
        "payloadType": "str",
        "topic": "",
        "x": 940,
        "y": 100,
        "wires": [
            [
                "d34d5904.4c1318"
            ]
        ]
    },
    {
        "id": "a50818a9.c0f618",
        "type": "exec",
        "z": "5604c6aa.1aabd8",
        "command": "wget -qO- http://ipecho.net/plain ; echo",
        "addpay": false,
        "append": "",
        "useSpawn": "false",
        "timer": "",
        "oldrc": false,
        "name": "",
        "x": 1400,
        "y": 660,
        "wires": [
            [
                "3d4a4865.dc1e48",
                "7a5cb7c6.7b1708",
                "8cf19604.8d12d8"
            ],
            [],
            []
        ]
    },
    {
        "id": "3d4a4865.dc1e48",
        "type": "debug",
        "z": "5604c6aa.1aabd8",
        "name": "",
        "active": true,
        "tosidebar": false,
        "console": false,
        "tostatus": true,
        "complete": "payload",
        "targetType": "msg",
        "x": 1690,
        "y": 640,
        "wires": []
    },
    {
        "id": "3d4bada.f3ae152",
        "type": "inject",
        "z": "5604c6aa.1aabd8",
        "name": "Now & 08:00",
        "repeat": "",
        "crontab": "00 08 * * *",
        "once": false,
        "onceDelay": 0.1,
        "topic": "",
        "payload": "Now",
        "payloadType": "str",
        "x": 700,
        "y": 640,
        "wires": [
            [
                "3adf8ce6.c312e4"
            ]
        ]
    },
    {
        "id": "ee3bfe2b.b5522",
        "type": "start-up-trigger",
        "z": "5604c6aa.1aabd8",
        "x": 80,
        "y": 380,
        "wires": [
            [
                "89c8db1.6be7128"
            ]
        ]
    },
    {
        "id": "89c8db1.6be7128",
        "type": "delay",
        "z": "5604c6aa.1aabd8",
        "name": "",
        "pauseType": "delay",
        "timeout": "5",
        "timeoutUnits": "minutes",
        "rate": "1",
        "nbRateUnits": "1",
        "rateUnits": "second",
        "randomFirst": "1",
        "randomLast": "5",
        "randomUnits": "seconds",
        "drop": false,
        "x": 260,
        "y": 380,
        "wires": [
            [
                "3adf8ce6.c312e4",
                "d34d5904.4c1318"
            ]
        ]
    },
    {
        "id": "7a5cb7c6.7b1708",
        "type": "ui_button",
        "z": "5604c6aa.1aabd8",
        "name": "External IP",
        "group": "e9824075.26cba",
        "order": 1,
        "width": 0,
        "height": 0,
        "passthru": false,
        "label": "External IP {{msg.payload}}",
        "tooltip": "",
        "color": "",
        "bgcolor": "",
        "icon": "",
        "payload": "now",
        "payloadType": "str",
        "topic": "",
        "x": 1090,
        "y": 800,
        "wires": [
            [
                "3adf8ce6.c312e4"
            ]
        ]
    },
    {
        "id": "21c0e6d2.0722ba",
        "type": "switch",
        "z": "5604c6aa.1aabd8",
        "name": "Refresh?",
        "property": "payload",
        "propertyType": "msg",
        "rules": [
            {
                "t": "eq",
                "v": "refresh",
                "vt": "str"
            }
        ],
        "checkall": "true",
        "repair": false,
        "outputs": 1,
        "x": 1090,
        "y": 560,
        "wires": [
            [
                "a50818a9.c0f618"
            ]
        ]
    },
    {
        "id": "b0e87457.b1a6f8",
        "type": "inject",
        "z": "5604c6aa.1aabd8",
        "name": "Red",
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "",
        "payload": "RED",
        "payloadType": "str",
        "x": 670,
        "y": 240,
        "wires": [
            [
                "a788bea2.bc90f"
            ]
        ]
    },
    {
        "id": "a788bea2.bc90f",
        "type": "change",
        "z": "5604c6aa.1aabd8",
        "name": "Move to msg.colour",
        "rules": [
            {
                "t": "move",
                "p": "payload",
                "pt": "msg",
                "to": "colour",
                "tot": "msg"
            }
        ],
        "action": "",
        "property": "",
        "from": "",
        "to": "",
        "reg": false,
        "x": 710,
        "y": 160,
        "wires": [
            [
                "de25758a.6fc028",
                "3c9fe1ac.52ebae"
            ]
        ]
    },
    {
        "id": "3c9fe1ac.52ebae",
        "type": "debug",
        "z": "5604c6aa.1aabd8",
        "name": "",
        "active": true,
        "tosidebar": false,
        "console": false,
        "tostatus": true,
        "complete": "colour",
        "targetType": "msg",
        "x": 930,
        "y": 140,
        "wires": []
    },
    {
        "id": "baa39aa9.b8b558",
        "type": "change",
        "z": "5604c6aa.1aabd8",
        "name": "Set to RED",
        "rules": [
            {
                "t": "set",
                "p": "colour",
                "pt": "msg",
                "to": "RED",
                "tot": "str"
            }
        ],
        "action": "",
        "property": "",
        "from": "",
        "to": "",
        "reg": false,
        "x": 1450,
        "y": 360,
        "wires": [
            [
                "d60908e0.a10998"
            ]
        ]
    },
    {
        "id": "2625872e.939748",
        "type": "change",
        "z": "5604c6aa.1aabd8",
        "name": "Set to GREEN",
        "rules": [
            {
                "t": "set",
                "p": "colour",
                "pt": "msg",
                "to": "GREEN",
                "tot": "str"
            }
        ],
        "action": "",
        "property": "",
        "from": "",
        "to": "",
        "reg": false,
        "x": 1680,
        "y": 340,
        "wires": [
            [
                "d60908e0.a10998"
            ]
        ]
    },
    {
        "id": "955e92.6a46417",
        "type": "inject",
        "z": "5604c6aa.1aabd8",
        "name": "Green",
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "",
        "payload": "GREEN",
        "payloadType": "str",
        "x": 670,
        "y": 300,
        "wires": [
            [
                "a788bea2.bc90f"
            ]
        ]
    },
    {
        "id": "49f41caf.ae4b84",
        "type": "inject",
        "z": "5604c6aa.1aabd8",
        "name": "Blue",
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "",
        "payload": "BLUE",
        "payloadType": "str",
        "x": 670,
        "y": 340,
        "wires": [
            [
                "a788bea2.bc90f"
            ]
        ]
    },
    {
        "id": "57bbcb23.acc604",
        "type": "link in",
        "z": "5604c6aa.1aabd8",
        "name": "VelServ Restart Button",
        "links": [
            "d60908e0.a10998"
        ],
        "x": 740,
        "y": 100,
        "wires": [
            [
                "de25758a.6fc028",
                "3c9fe1ac.52ebae"
            ]
        ]
    },
    {
        "id": "d60908e0.a10998",
        "type": "link out",
        "z": "5604c6aa.1aabd8",
        "name": "Set VelServ Restart colour",
        "links": [
            "57bbcb23.acc604"
        ],
        "x": 1835,
        "y": 360,
        "wires": []
    },
    {
        "id": "c68aa73b.600648",
        "type": "inject",
        "z": "5604c6aa.1aabd8",
        "d": true,
        "name": "Any trigger & 05:00",
        "repeat": "",
        "crontab": "00 05 * * *",
        "once": false,
        "onceDelay": 0.1,
        "topic": "",
        "payload": "",
        "payloadType": "date",
        "x": 1160,
        "y": 1000,
        "wires": [
            [
                "947e9e68.fdec9"
            ]
        ]
    },
    {
        "id": "66bd5cc9.6296d4",
        "type": "ui_button",
        "z": "5604c6aa.1aabd8",
        "name": "",
        "group": "e9824075.26cba",
        "order": 3,
        "width": 0,
        "height": 0,
        "passthru": false,
        "label": "Restart openHAB2",
        "tooltip": "",
        "color": "",
        "bgcolor": "{{colour}}",
        "icon": "",
        "payload": "now",
        "payloadType": "str",
        "topic": "",
        "x": 1190,
        "y": 1060,
        "wires": [
            [
                "947e9e68.fdec9"
            ]
        ]
    },
    {
        "id": "947e9e68.fdec9",
        "type": "exec",
        "z": "5604c6aa.1aabd8",
        "command": "sudo systemctl restart openhab2",
        "addpay": false,
        "append": "",
        "useSpawn": "false",
        "timer": "",
        "oldrc": false,
        "name": "Restart Velserv",
        "x": 1530,
        "y": 1060,
        "wires": [
            [
                "a3912690.88d108"
            ],
            [],
            []
        ]
    },
    {
        "id": "8732e9da.49baf8",
        "type": "debug",
        "z": "5604c6aa.1aabd8",
        "name": "",
        "active": true,
        "tosidebar": false,
        "console": false,
        "tostatus": true,
        "complete": "payload",
        "targetType": "msg",
        "x": 1790,
        "y": 1280,
        "wires": []
    },
    {
        "id": "3065ee8e.d562e2",
        "type": "switch",
        "z": "5604c6aa.1aabd8",
        "name": "Status",
        "property": "payload",
        "propertyType": "msg",
        "rules": [
            {
                "t": "eq",
                "v": "ON",
                "vt": "str"
            },
            {
                "t": "eq",
                "v": "OFF",
                "vt": "str"
            },
            {
                "t": "else"
            }
        ],
        "checkall": "false",
        "repair": false,
        "outputs": 3,
        "x": 1560,
        "y": 1280,
        "wires": [
            [
                "c28a8323.4be59"
            ],
            [
                "d3246aa6.3f7208"
            ],
            []
        ]
    },
    {
        "id": "d3246aa6.3f7208",
        "type": "change",
        "z": "5604c6aa.1aabd8",
        "name": "Set to RED",
        "rules": [
            {
                "t": "set",
                "p": "colour",
                "pt": "msg",
                "to": "RED",
                "tot": "str"
            }
        ],
        "action": "",
        "property": "",
        "from": "",
        "to": "",
        "reg": false,
        "x": 890,
        "y": 1080,
        "wires": [
            [
                "66bd5cc9.6296d4"
            ]
        ]
    },
    {
        "id": "c28a8323.4be59",
        "type": "change",
        "z": "5604c6aa.1aabd8",
        "name": "Set to GREEN",
        "rules": [
            {
                "t": "set",
                "p": "colour",
                "pt": "msg",
                "to": "GREEN",
                "tot": "str"
            }
        ],
        "action": "",
        "property": "",
        "from": "",
        "to": "",
        "reg": false,
        "x": 900,
        "y": 1140,
        "wires": [
            [
                "66bd5cc9.6296d4"
            ]
        ]
    },
    {
        "id": "a3912690.88d108",
        "type": "change",
        "z": "5604c6aa.1aabd8",
        "name": "Set to ORANGE",
        "rules": [
            {
                "t": "set",
                "p": "colour",
                "pt": "msg",
                "to": "ORANGE",
                "tot": "str"
            }
        ],
        "action": "",
        "property": "",
        "from": "",
        "to": "",
        "reg": false,
        "x": 1220,
        "y": 1120,
        "wires": [
            [
                "66bd5cc9.6296d4"
            ]
        ]
    },
    {
        "id": "3adf8ce6.c312e4",
        "type": "looptimer",
        "z": "5604c6aa.1aabd8",
        "duration": "6",
        "units": "Hour",
        "maxloops": "999999999",
        "maxtimeout": "999999999",
        "maxtimeoutunits": "Hour",
        "name": "",
        "x": 1090,
        "y": 720,
        "wires": [
            [
                "a50818a9.c0f618"
            ],
            []
        ]
    },
    {
        "id": "609cc900.5bfb68",
        "type": "openhab2-monitor2",
        "z": "5604c6aa.1aabd8",
        "name": "Monitor",
        "controller": "3502c5bb.807e8a",
        "x": 930,
        "y": 1280,
        "wires": [
            [
                "4affcad5.7abbb4",
                "3065ee8e.d562e2"
            ],
            [],
            []
        ]
    },
    {
        "id": "4affcad5.7abbb4",
        "type": "debug",
        "z": "5604c6aa.1aabd8",
        "name": "",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": true,
        "complete": "true",
        "targetType": "full",
        "statusVal": "payload",
        "statusType": "msg",
        "x": 1190,
        "y": 1380,
        "wires": []
    },
    {
        "id": "692ef8d2.1603c8",
        "type": "openhab2-in2",
        "z": "5604c6aa.1aabd8",
        "name": "Velbus Reset",
        "controller": "3502c5bb.807e8a",
        "itemname": "VelbusRefresh",
        "topic": "",
        "initialstate": false,
        "whenupdated": true,
        "whencommand": true,
        "whenchanged": false,
        "changedfrom": "",
        "changedto": "",
        "x": 890,
        "y": 220,
        "wires": [
            [
                "71cd35e9.972d4c",
                "1d4b0b05.eb8905"
            ]
        ]
    },
    {
        "id": "71cd35e9.972d4c",
        "type": "switch",
        "z": "5604c6aa.1aabd8",
        "name": "",
        "property": "payload",
        "propertyType": "msg",
        "rules": [
            {
                "t": "eq",
                "v": "Restart",
                "vt": "str"
            }
        ],
        "checkall": "true",
        "repair": false,
        "outputs": 1,
        "x": 1060,
        "y": 220,
        "wires": [
            [
                "d34d5904.4c1318"
            ]
        ]
    },
    {
        "id": "1d4b0b05.eb8905",
        "type": "debug",
        "z": "5604c6aa.1aabd8",
        "name": "",
        "active": true,
        "tosidebar": false,
        "console": false,
        "tostatus": true,
        "complete": "payload",
        "targetType": "msg",
        "statusVal": "payload",
        "statusType": "auto",
        "x": 1030,
        "y": 280,
        "wires": []
    },
    {
        "id": "8cf19604.8d12e8",
        "type": "openhab2-out2",
        "z": "5604c6aa.1aabd8",
        "name": "VelbusRefresh",
        "controller": "3502c5bb.807e8a",
        "itemname": "VelbusRefresh",
        "topic": "ItemCommand",
        "payload": "",
        "onlywhenchanged": false,
        "x": 2140,
        "y": 280,
        "wires": []
    },
    {
        "id": "ef0a8e18.fe027",
        "type": "change",
        "z": "5604c6aa.1aabd8",
        "name": "Restarting",
        "rules": [
            {
                "t": "set",
                "p": "payload",
                "pt": "msg",
                "to": "Restarting",
                "tot": "str"
            }
        ],
        "action": "",
        "property": "",
        "from": "",
        "to": "",
        "reg": false,
        "x": 1610,
        "y": 80,
        "wires": [
            [
                "8cf19604.8d12e8"
            ]
        ]
    },
    {
        "id": "41be273b.b1aa48",
        "type": "change",
        "z": "5604c6aa.1aabd8",
        "name": "Running",
        "rules": [
            {
                "t": "set",
                "p": "payload",
                "pt": "msg",
                "to": "Running",
                "tot": "str"
            }
        ],
        "action": "",
        "property": "",
        "from": "",
        "to": "",
        "reg": false,
        "x": 1920,
        "y": 280,
        "wires": [
            [
                "8cf19604.8d12e8"
            ]
        ]
    },
    {
        "id": "8cf19604.8d12d8",
        "type": "openhab2-out2",
        "z": "5604c6aa.1aabd8",
        "name": "External IP",
        "controller": "3502c5bb.807e8a",
        "itemname": "ExternalIP",
        "topic": "ItemCommand",
        "payload": "",
        "onlywhenchanged": false,
        "x": 1710,
        "y": 780,
        "wires": []
    },
    {
        "id": "692ef8d2.1653a8",
        "type": "openhab2-in2",
        "z": "5604c6aa.1aabd8",
        "name": "External IP",
        "controller": "3502c5bb.807e8a",
        "itemname": "ExternalIP",
        "topic": "",
        "initialstate": false,
        "whenupdated": true,
        "whencommand": true,
        "whenchanged": false,
        "changedfrom": "",
        "changedto": "",
        "x": 840,
        "y": 560,
        "wires": [
            [
                "21c0e6d2.0722ba"
            ]
        ]
    },
    {
        "id": "e9824075.26cba",
        "type": "ui_group",
        "name": "System",
        "tab": "ebb962f5.47aa7",
        "order": 1,
        "disp": true,
        "width": "6",
        "collapse": true
    },
    {
        "id": "3502c5bb.807e8a",
        "type": "openhab2-controller2",
        "name": "openHAB3",
        "protocol": "http",
        "host": "localhost",
        "port": "8080",
        "path": "",
        "username": "oh.NodeRED.gjjqDn66jfnwGgd7SBv9COxZfgFvXezGeTzL4TEbns1DxRjkHkqsybjUApkYGWgmP4bTq5xAIJEjwlp2Ig",
        "password": "",
        "ohversion": "v3"
    },
    {
        "id": "ebb962f5.47aa7",
        "type": "ui_tab",
        "z": "5604c6aa.1aabd8",
        "name": "Maintance",
        "icon": "dashboard",
        "disabled": false,
        "hidden": false
    }
]
```

**Comment by tomassobe** [comment]
I'm having a similar issue

**Comment by MDAR** [comment]
I can confirm that I've just tried this with a fresh installation of Node-RED V1.3.5 and OpenHAB3 on an Odroid C2, with the same results.

The Monitor node happily shows Items in the third output and the On-Line state from output 1

But the IN and OUT nodes are unable to populate the drop-down list.

The only way to get the nodes to work is export , import and edit the ItemName

@jeroenhendricksen 
Your help would be most appriecated

**Comment by jeroenhendricksen** [comment]
I'll try to have a look later this week.

**Comment by MDAR** [comment]
> I'll try to have a look later this week.

If there is anything I can do to help, please ask (including a remote connection if it helps)

**Comment by jeroenhendricksen** [comment]
> > I'll try to have a look later this week.
> 
> If there is anything I can do to help, please ask (including a remote connection if it helps)
> 
> FYI
> 
> I get a flood of output from the openHAB2-events2 node
> 
> Nothing now from the openhab2-Monitor
> 
> Get, In and Out work, but only because I set the Items during the import process (drop down lists aren't populating)
> 
> I did just see a Warning in the log, "`[ore.io.rest.auth.internal.AuthfFilter] - Unauthorised API request: Invalid Basic authenticaion credentials`" but that didn't correspond with anything I have been doing.

Thank you for the additional information. First off, I'm trying to reproduce the problem in the [docker setup](https://github.com/jeroenhendricksen/node-red-contrib-openhab3/blob/master/README.md) I've created for testing the plugin with OpenHAB 2 and 3 simultaneously. It would be really helpful if you could reproduce it in that environment.

**Comment by jeroenhendricksen** [comment]
I've just verified that the test setup (with the default "authentication" for OH2 and OH3) still works with populating Items, even when I comment all the items (and save the file) and uncomment them (and save the file) later on. The items list in NodeRED gets populated in each situation, though of course it is empty when the Items list in OH is empty. This requires no restart of any service.

I'll now try with a "basic auth protected" OH3...

**Comment by MDAR** [comment]
> with the default "authentication" for OH2 and OH3

Hold on a moment...

Are you suggesting that there is a set of default credentials?


I've been creating an APi code and using that 

Am I doing too much???

**Comment by MDAR** [comment]
> It would be really helpful if you could reproduce it in that environment.

I'm happy to open up a port to a test computer if you want to

**Comment by jeroenhendricksen** [comment]
I'm still exploring, but let me share what I have so far:

When you start OH3 from docker (in a clean setup) it's unprotected. When you visit the UI (http://localhost:8081 in my test setup), you are welcomed with a screen where you must set a username/password. I've done that, setting `admin`/`admin`, plus I've setup other things from the setup wizard (which are irrelevant for this issue I think).

The node-red plugin works by providing an endpoint with nodered that can be queried for getting a list of items. In my test setup case that is http://localhost:1880/openhab2/items 

Under the hood, the nodered plugin tries to request all OH items by requesting the list of items via http://localhost:8081/rest/items

It seems this endpoint is not protected, even after I've set the username/password in the UI. It seems the OH3 API exposes a read-only version of this items endpoint.

Proof that this works (without authentication):
curl http://localhost:8081/rest/items

The event stream can also be read without authentication:
curl http://localhost:8081/rest/events?topics=openhab/*/*

However, providing basic authentication credentials break the request:
$curl -u admin:admin http://localhost:8081/rest/items

Response:
"error":{"message":"Invalid credentials","http-code":401}}

Now I've provided the OH3 connection in NodeRED with a username and password (admin/admin) the connection fails with the same error you've mentioned:
`17:55:30.138 [WARN ] [ore.io.rest.auth.internal.AuthFilter] - Unauthorized API request: Invalid Basic authentication credentials` 

This was expected, given that basic authentication above with curl returns a 401.

When I look at the settings of OH3, it seems OAuth2 is now supported. So I've created a token for the admin user, and when I then perform a request with the token in the header, it works again:

`curl --header "Authorization: Bearer oh.nodered.TOKEN" http://localhost:8081/rest/items/`
and also:
`curl -H "Authentication: Bearer oh.nodered.TOKEN" http://localhost:8081/rest/events\?topics\=openhab/\*/\*` (for the evtn stream)

So, how to fix this? When you walk through the OH3 wizard, which everyone probably does by default, this is not the source of any problem. However when you set the username and password, it breaks all communication with OH3, because OH# doesn't support basic auth by itself (it throws 401).
I could add support for providing a token with regards to OH3 configuration and use it in all request as a Authentication header.

However, with regards to authentication, the [OpenHAB docs on security](https://www.openhab.org/docs/installation/security.html) are not really clear here:
_openHAB does not (yet) support restricting access through HTTP(S) for certain users - there is no authentication in place, nor is there a limitation of functionality or information that different users can access._
So the basic authentication feature was probably meant when you have a (for example) nginx reverse proxy with basic authentication placed before OH3.

> I'm happy to open up a port to a test computer if you want to test your docker Node-RED against my openHAB setup?

Thank you for the offer, but as it seems I have reproduced the issue locally, I prefer no to make it more complex by testing against another setup

> Hold on a moment...
> Are you suggesting that there is a set of default credentials?
> I've been creating an APi code and using that
> Am I doing too much???

It seems that when NodeRED can communicate directly with OpenHAB3 (with no reverse proxy with basic auth in between), you are better off with providing an empty username and passwords. That's the setup I've been testing all along and which works.

I'll check if the plugin can be restored to normal operation when removing the username/password from the config again...

**Comment by jeroenhendricksen** [comment]
What I found:

- I can "restore" the plugin workings for my local environment when I remove the username and password for the openhab3 connection. This is a work-around for then there is no reverse proxy with basic authentication in place.
- It does't seem the matter if and with what token you open up a connection to the eventstream endpoint:
  - Works: `curl -H "Authentication: Bearer oh.nodered.VALIDTOKEN" http://localhost:8081/rest/events\?topics\=openhab/\*/\*`
  - Works: `curl -H "Authentication: Bearer whatever-floats-your-boat" http://localhost:8081/rest/events\?topics\=openhab/\*/\*`
  - 401 Invalid credentials: `curl -u "admin:admin" http://localhost:8081/rest/events\?topics\=openhab/\*/\*`

Do you have a reverse proxy with basic authentication running in front of your OH3 instance?

**Comment by MDAR** [comment]
> What I found:
> 
> * I can "restore" the plugin workings for my local environment when I remove the username and password for the openhab3 connection. This is a work-around for when there is no reverse proxy with basic authentication in place.
> * It does't seem the matter if and with what token you open up a connection to the eventstream endpoint:
>   
>   * Works: `curl -H "Authentication: Bearer oh.nodered.VALIDTOKEN" http://localhost:8081/rest/events\?topics\=openhab/\*/\*`
>   * Works: `curl -H "Authentication: Bearer whatever-floats-your-boat" http://localhost:8081/rest/events\?topics\=openhab/\*/\*`
>   * 401 Invalid credentials: `curl -u "admin:admin" http://localhost:8081/rest/events\?topics\=openhab/\*/\*`
> 
> Do you have a reverse proxy with basic authentication running in front of your OH3 instance? What happens when you remove username _and_ password for your openhab3 connection in the nodered plugin?

Well .... that's where I have been going wrong.

I was following instructions that said I needed to use an API or credentials

I've got a completely clean machine on the go now, that I haven't even gone past the first page

![image](https://user-images.githubusercontent.com/10905891/119887799-7fe34880-bf2c-11eb-9de5-a7ad4d1406d8.png)


So it's sitting without any form of interaction, other than me dropping a test.items file in place.

```
Number Number1 "test number 1"
Number Number2 "test number 2"
String String1 "test string 1"
String ExternalIP "External IP"
String VelbusRefresh "Velbus Refresh"
```

Which are all clearly shown in the Out & IN nodes now

![image](https://user-images.githubusercontent.com/10905891/119888006-c5077a80-bf2c-11eb-930c-d01a8aec463c.png)


And this is all I have in the Controller config

![image](https://user-images.githubusercontent.com/10905891/119888061-d51f5a00-bf2c-11eb-86d8-60c71dadf0e3.png)


HOWEVER

As you suggest, when it comes to writing new values, I see this error

`response error '{"statusCode":415,"body":"","headers":{"connection":"close","date":"Thu, 27 May 2021 19:51:23 GMT","content-length":"0","server":"Jetty(9.4.20.v20190813)"},"request":{"uri":{"protocol":"http:","slashes":true,"auth":null,"host":"127.0.0.1:8080","port":"8080","hostname":"127.0.0.1","hash":null,"search":null,"query":null,"pathname":"/rest/items/VelbusRefresh/state","path":"/rest/items/VelbusRefresh/state","href":"http://127.0.0.1:8080/rest/items/VelbusRefresh/state"},"method":"PUT","headers":{"content-length":7}}}' on 'http://127.0.0.1:8080/rest/items/VelbusRefresh/state'`

**Comment by jeroenhendricksen** [comment]
> As you suggest, when it comes to writing new values, I see this error
> 
> `response error '{"statusCode":415,"body":"","headers":{"connection":"close","date":"Thu, 27 May 2021 19:51:23 GMT","content-length":"0","server":"Jetty(9.4.20.v20190813)"},"request":{"uri":{"protocol":"http:","slashes":true,"auth":null,"host":"127.0.0.1:8080","port":"8080","hostname":"127.0.0.1","hash":null,"search":null,"query":null,"pathname":"/rest/items/VelbusRefresh/state","path":"/rest/items/VelbusRefresh/state","href":"http://127.0.0.1:8080/rest/items/VelbusRefresh/state"},"method":"PUT","headers":{"content-length":7}}}' on 'http://127.0.0.1:8080/rest/items/VelbusRefresh/state'`

So I've also started a clean openhab3, but I can update item and group states using an `openhab2-out2` node. With what process/endpoint are you trying to write the `VelbusRefresh` state?

**Comment by MDAR** [comment]
> So I've also started a clean openhab3, but I can update item and group states using an `openhab2-out2` node. With what process/endpoint are you trying to write the `VelbusRefresh` state?

That's very odd.

That's almost exactly how I've got this machine setup.

I'm using the flow as shown above with these items.


The update for the VelbusRefresh node is nothing more than an Out node, with a payload of "running"

**Comment by jeroenhendricksen** [comment]
I stop working on this for tonight, but will continue at a later moment. I already started working on adding support for OAuth2 tokens for OH3 connections, as I think we need this to have a more future proof solution.

**Comment by jeroenhendricksen** [comment]
> > So I've also started a clean openhab3, but I can update item and group states using an `openhab2-out2` node. With what process/endpoint are you trying to write the `VelbusRefresh` state?
> 
> That's very odd.
> 
> That's almost exactly how I've got this machine setup.
> 
> I'm using the flow as shown above with these items.
> 
> The update for the VelbusRefresh node is nothing more than an Out node, with a payload of "running"

Id hadn't tried your flow yet, just my [own test flow](https://github.com/jeroenhendricksen/node-red-contrib-openhab3/blob/master/test/nodered/flow.json). I'll give yours a try, maybe that helps me to reproduce.

**Comment by MDAR** [comment]
Thank you for all your efforts.

I really wasn't expecting your input so quickly.

Good evening 😄

**Comment by jeroenhendricksen** [comment]
> > So I've also started a clean openhab3, but I can update item and group states using an `openhab2-out2` node. With what process/endpoint are you trying to write the `VelbusRefresh` state?
> 
> That's very odd.
> 
> That's almost exactly how I've got this machine setup.
> 
> I'm using the flow as shown above with these items.
> 
> The update for the VelbusRefresh node is nothing more than an Out node, with a payload of "running"

I've loaded your flow. Though some nodes where of types that where not supported, I could access your controller config. What I don't understand is why I don't see the version dropdown where you can specify v2 or v3. Have you omitted it from the screenshot?
What version of the plugin are you running? Can you maybe upgrade to `1.3.5`?

This is what your flow looks like in my 1.3.6 screen:
<img width="506" alt="Screenshot 2021-05-27 at 22 22 43" src="https://user-images.githubusercontent.com/32140294/119892501-8082db80-bf3a-11eb-954f-e0c90ecf71d5.png">

**Comment by jeroenhendricksen** [comment]
To avoid any further confusion, I was talking about the plugin needing to be at version 1.3.5, but Node-RED itself happens to be at version 1.3.5 too. What a coincidence! :)

**Comment by MDAR** [comment]
> To avoid any further confusion, I was talking about the plugin needing to be at version 1.3.5, but Node-RED itself happens to be at version 1.3.5 too. What a coincidence! :)

Yes indeed, your node set is shown a# V1.3.5 and Node-RED is showing V1.3.5

And yes, I did foolishly miss the bottom of the Controller screen grab.

So with an API in the user name (as suggested by someone on the openHAB forum) does look like this

![image](https://user-images.githubusercontent.com/10905891/119893685-93de7880-bf33-11eb-9e6e-80789193d14f.png)

**Comment by MDAR** [comment]
If you send me an email, I'll send you the `Velbus Bridge Thing` configuration file, so you can bypass openHAB here and link directly to the demo rig.
If you want to see live data

Support2021 (at) mdar.eu

**Comment by jeroenhendricksen** [comment]
I've releases version 1.3.6 which has OAuth2 support. Can you give this a try?
Please don't follow the instructions [here](https://www.openhab.org/docs/configuration/apitokens.html), but only fill the newly added `OAuth2 Bearer token` field with a working token. Don't use the Username/Password field (leave them empty), unless you are using some kind of proxy running in front of OpenHAB3 that forces basic authentication.

**Comment by MDAR** [comment]
Hi

thank you for working on this.

I have updated your nodes and restarted Node-Red.

I moved the API Token from the username to your new API field.

when I deployed the flow, node-red crashed and continues to crash every time I restart it.

The `systemctl status node-red` command returns this after about 1 second of re-starting each time (afterwards)

```
Using username "root".
Linux openHAB2-C4 4.9.241-arm64 #1 SMP PREEMPT Thu Feb 25 17:57:15 CET 2021 aarc                                                                                                                       h64

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
Last login: Mon May 31 11:36:29 2021
 ─────────────────────────────────────────────────────
 DietPi v7.2.3 : 11:43 - Mon 31/05/21
 ─────────────────────────────────────────────────────
 - Device model : Odroid C4/HC4 (aarch64)
 - CPU temp : 41'C : 105'F (Optimal temperature)
 - LAN IP : 192.168.178.89 (eth0)
 - MOTD : DietPi v7.2 has been released, please update now.
 ─────────────────────────────────────────────────────

 DietPi Team     : MichaIng (lead), Daniel Knight (founder), Joulinar (support)
 Image by        : DietPi Core Team (pre-image: Meveric)
 Web             : https://dietpi.com | https://twitter.com/DietPi_
 Patreon Legends : Camry2731
 Contribute      : https://dietpi.com/contribute.html
 DietPi Hosting  : Powered by https://myvirtualserver.com

 dietpi-launcher : All the DietPi programs in one place.
 dietpi-config   : Feature rich configuration tool for your device.
 dietpi-software : Select optimized software for installation.
 htop            : Resource monitor.
 cpu             : Shows CPU information and stats.

root@openHAB2-C4:~# systemctl restart node-red


root@openHAB2-C4:~# systemctl status node-red
● node-red.service - Node-RED (DietPi)
   Loaded: loaded (/etc/systemd/system/node-red.service; disabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Mon 2021-05-31 11:44:06 BST; 1min 20s ago
  Process: 5656 ExecStart=/mnt/dietpi_userdata/node-red/node_modules/.bin/node-red -u /mnt/dietpi_userdata/node-red (code=exited, status=1/FAILURE)
 Main PID: 5656 (code=exited, status=1/FAILURE)

May 31 11:44:05 openHAB2-C4 node-red[5656]: ---------------------------------------------------------------------
May 31 11:44:05 openHAB2-C4 node-red[5656]: 31 May 11:44:05 - [info] Starting flows
May 31 11:44:05 openHAB2-C4 node-red[5656]: 31 May 11:44:05 - [info] Started flows
May 31 11:44:06 openHAB2-C4 node-red[5656]: 31 May 11:44:06 - [red] Uncaught Exception:
May 31 11:44:06 openHAB2-C4 node-red[5656]: 31 May 11:44:06 - TypeError: Cannot read property 'control' of null
May 31 11:44:06 openHAB2-C4 node-red[5656]:     at Timeout.getInitial [as _onTimeout] (/mnt/dietpi_userdata/node-red/node_modules/node-red-contrib-openhab3/77-openhab2.js:396:31)
May 31 11:44:06 openHAB2-C4 node-red[5656]:     at listOnTimeout (node:internal/timers:557:17)
May 31 11:44:06 openHAB2-C4 node-red[5656]:     at processTimers (node:internal/timers:500:7)
May 31 11:44:06 openHAB2-C4 systemd[1]: node-red.service: Main process exited, code=exited, status=1/FAILURE
May 31 11:44:06 openHAB2-C4 systemd[1]: node-red.service: Failed with result 'exit-code'.
root@openHAB2-C4:~#
```

**Comment by MDAR** [comment]
BUT!!!!!!!!

**Comment by jeroenhendricksen** [comment]
> 77-openhab2.js:396:31

Thank you for reporting this stacktrace.
This means openhabController was null, which already has a check for it in the code in at least 1 place:

```
var openhabController = RED.nodes.getNode(config.controller);
if (openhabController == null) {
    node.error("Invalid controller");
    return;
}
```

so I've repeated this code for every occurrence of `RED.nodes.getNode(config.controller);`. This doesn't solve the issue (the plugin configuration cannot be interpreted!? The plugin was not properly installed?), but at least it will show a decent error in the NodeRED log and not a stacktrace. It is released as 1.3.7

**Comment by guny74** [comment]
Hello,

I have the same issue. I have the latest Version, but no selection of items is possible.

**Comment by MDAR** [comment]
Hi

I experienced this again yesterday.

I updated openHAB 3 *and* the openHAB node set to discover their is more a new field for entering the APi access code.


It worked instantly.

**Comment by guny74** [comment]
I use this new field, with no success.

No Error (faund), but also not item selection possible.

**Comment by MDAR** [comment]
> I use this new field, with no success.
> 
> No Error (faund), but also not item selection possible.

I'm sorry you are having issues.

I'm not a developer, so can only say what I have done as a user in order to get it working.

(Sorry if I repeat things you already know)

in openHAB, create an API key

In Settings > API Security
![image](https://user-images.githubusercontent.com/10905891/131824657-fbe7940b-b060-43c1-b584-5bf0392fad87.png)


in Node-RED (Which I have got working with V1.3.6 and V2.0.6)
Use these modules
openHAB3 - https://flows.nodered.org/node/node-red-contrib-openhab3
![image](https://user-images.githubusercontent.com/10905891/131824772-00570834-d86a-4197-805b-6025a76cd949.png)


In the controller config 
![image](https://user-images.githubusercontent.com/10905891/131824973-7a0176ec-1ebd-4e30-8378-3d5031dc8370.png)

That should be everything working.

I have created a little Node-RED dashboard to show the status of openHAB (and restart it)

```
[
    {
        "id": "af4f0303.5d0dd",
        "type": "inject",
        "z": "8f102804.c809b8",
        "d": true,
        "name": "Any trigger & 05:00",
        "repeat": "",
        "crontab": "00 05 * * *",
        "once": false,
        "onceDelay": 0.1,
        "topic": "",
        "payload": "",
        "payloadType": "date",
        "x": 620,
        "y": 1480,
        "wires": [
            [
                "dcf598b.8258868"
            ]
        ]
    },
    {
        "id": "67c82d22.b005a4",
        "type": "ui_button",
        "z": "8f102804.c809b8",
        "name": "",
        "group": "2524e151.c64fbe",
        "order": 4,
        "width": 0,
        "height": 0,
        "passthru": false,
        "label": "Restart openHAB",
        "tooltip": "",
        "color": "",
        "bgcolor": "{{colour}}",
        "icon": "",
        "payload": "now",
        "payloadType": "str",
        "topic": "",
        "topicType": "str",
        "x": 650,
        "y": 1540,
        "wires": [
            [
                "dcf598b.8258868"
            ]
        ]
    },
    {
        "id": "dcf598b.8258868",
        "type": "exec",
        "z": "8f102804.c809b8",
        "command": "sudo systemctl restart openhab",
        "addpay": false,
        "append": "",
        "useSpawn": "false",
        "timer": "",
        "oldrc": false,
        "name": "Restart openHAB",
        "x": 1000,
        "y": 1540,
        "wires": [
            [
                "99fc77ea.722968"
            ],
            [],
            []
        ]
    },
    {
        "id": "a1c9b597.fc1eb8",
        "type": "change",
        "z": "8f102804.c809b8",
        "name": "Set to RED",
        "rules": [
            {
                "t": "set",
                "p": "colour",
                "pt": "msg",
                "to": "RED",
                "tot": "str"
            }
        ],
        "action": "",
        "property": "",
        "from": "",
        "to": "",
        "reg": false,
        "x": 350,
        "y": 1560,
        "wires": [
            [
                "67c82d22.b005a4"
            ]
        ]
    },
    {
        "id": "cd33e6c2.9d85f8",
        "type": "change",
        "z": "8f102804.c809b8",
        "name": "Set to GREEN",
        "rules": [
            {
                "t": "set",
                "p": "colour",
                "pt": "msg",
                "to": "GREEN",
                "tot": "str"
            }
        ],
        "action": "",
        "property": "",
        "from": "",
        "to": "",
        "reg": false,
        "x": 360,
        "y": 1620,
        "wires": [
            [
                "67c82d22.b005a4"
            ]
        ]
    },
    {
        "id": "99fc77ea.722968",
        "type": "change",
        "z": "8f102804.c809b8",
        "name": "Set to ORANGE",
        "rules": [
            {
                "t": "set",
                "p": "colour",
                "pt": "msg",
                "to": "ORANGE",
                "tot": "str"
            }
        ],
        "action": "",
        "property": "",
        "from": "",
        "to": "",
        "reg": false,
        "x": 680,
        "y": 1600,
        "wires": [
            [
                "67c82d22.b005a4"
            ]
        ]
    },
    {
        "id": "a4ed61e0.a0c7b",
        "type": "switch",
        "z": "8f102804.c809b8",
        "name": "Status",
        "property": "payload",
        "propertyType": "msg",
        "rules": [
            {
                "t": "eq",
                "v": "ON",
                "vt": "str"
            },
            {
                "t": "eq",
                "v": "OFF",
                "vt": "str"
            },
            {
                "t": "else"
            }
        ],
        "checkall": "false",
        "repair": false,
        "outputs": 3,
        "x": 1020,
        "y": 1760,
        "wires": [
            [
                "cd33e6c2.9d85f8"
            ],
            [
                "a1c9b597.fc1eb8"
            ],
            []
        ]
    },
    {
        "id": "343fc613.295daa",
        "type": "debug",
        "z": "8f102804.c809b8",
        "name": "",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": true,
        "complete": "true",
        "targetType": "full",
        "statusVal": "payload",
        "statusType": "msg",
        "x": 710,
        "y": 1800,
        "wires": []
    },
    {
        "id": "d56af9a2.8390e8",
        "type": "openhab2-monitor2",
        "z": "8f102804.c809b8",
        "name": "openHAB3 Status",
        "controller": "3baf0e48.74a902",
        "x": 320,
        "y": 1760,
        "wires": [
            [
                "343fc613.295daa",
                "a4ed61e0.a0c7b"
            ],
            [],
            []
        ]
    },
    {
        "id": "2524e151.c64fbe",
        "type": "ui_group",
        "name": "Exec Commands",
        "tab": "263265dc.c8565a",
        "order": 3,
        "disp": true,
        "width": "6",
        "collapse": true
    },
    {
        "id": "3baf0e48.74a902",
        "type": "openhab2-controller2",
        "name": "Local openHAB3",
        "protocol": "http",
        "host": "127.0.0.1",
        "port": "8080",
        "path": "",
        "username": "",
        "password": "",
        "ohversion": "v3",
        "token": "YourToken"
    },
    {
        "id": "263265dc.c8565a",
        "type": "ui_tab",
        "name": "Home",
        "icon": "dashboard",
        "disabled": false,
        "hidden": false
    }
]
```

**Comment by jeroenvdd** [comment]
Hi sorry to bust this topic again,
but I have the same issue no item selection possible,
but when i use openhab2 monitor -> i get all the events

OH version 3.1
nodered 10.1.0

nodred is running on an other server just to be clear :)

**Comment by MDAR** [comment]
Hi @jeroenvdd 

I'm having plenty of success now, so very surprised to hear you're having issues.

Check list

* Have you got the very latest version of the nodes?
* Are you using a OH3 APi token in the controller setup, in the token field, with username and password blank?

I haven't tried going across machines, but happy to give it a try for you when I get back to my office tomorrow.

**Comment by jeroenvdd** [comment]
![Token](https://user-images.githubusercontent.com/6975276/142227883-0532fc54-1052-478b-bfc8-5d5afd376918.PNG)

these are the settings in node red (clean new version V2.1.3)

does basic auth need to be toggled or not in openhab? (the internet is full of contradictions (not that I haven't tried both) ) :)

**Comment by jeroenhendricksen** [comment]
> ![Token](https://user-images.githubusercontent.com/6975276/142227883-0532fc54-1052-478b-bfc8-5d5afd376918.PNG)
> 
> got the token here: ![image](https://user-images.githubusercontent.com/6975276/142228430-ca98790f-cc3f-457d-a58e-9c713281b616.png)
> 
> these are the settings in node red (clean new version V2.1.3)
> 
> does basic auth need to be toggled or not in openhab? (the internet is full of contradictions (not that I haven't tried both) ) :)

I wasn't aware openhab3 has a basic authentication feature by itself. Maybe that's a feature of the openhabian image or the nginx or traefic reverse proxy it (probably) installs?
I've tested the (complete literal) token without any basic authentication being in place, and if that's the case for you, you should leave username and password empty.

**Comment by jeroenvdd** [comment]
Ok thx for the reply,
so basicly my 'settings' seem to align with the settings as they should be,
could this give a hint:
![image](https://user-images.githubusercontent.com/6975276/142232135-350efe4e-1c17-471e-a382-4c63d660017c.png)

**Comment by jeroenhendricksen** [comment]
> Ok thx for the reply, so basicly my 'settings' seem to align with the settings as they should be, could this give a hint: ![image](https://user-images.githubusercontent.com/6975276/142232135-350efe4e-1c17-471e-a382-4c63d660017c.png)

Obviously it's related to authentication, but I can't tell the reason looking at this screenshot (though it help with the context).

What happens when you try to the following cases (replacing the relevant variables) from 
a) a shell on openhabian and 
b) a machine in the same network as openhabian (your own pc for example)?

1. `curl -XGET http://openhabian-ip-or-domain-name/rest/items` --> I expect a 200 in both cases
2. `curl -XGET --header 'Authorization: Bearer OAUTHTOKEN_HERE' http://openhabian-ip-or-domain-name/rest/items` --> I also expect a 200 in both cases

^ If 1. works, this would prove that basic authentication is probably not interfering.
Also, if 2. works, it would prove that the oauth token is correct and enabled.

**Comment by jeroenhendricksen** [comment]
I also found this in the openhab3 docs [here](https://www.openhab.org/docs/installation/security.html)

<img width="1274" alt="Screenshot 2021-11-17 at 17 40 06" src="https://user-images.githubusercontent.com/32140294/142243130-950fb022-7146-4703-baef-e8f9ed9e2fb7.png">

So you should figure out what nginx is doing and how it is set-up. If you tell me, I can probably fix this problem for you.

Maybe it's also possible for me to add openhabian to the docker test I've set up, but that won't help you in the short term.

**Comment by jeroenvdd** [comment]
> > Ok thx for the reply, so basicly my 'settings' seem to align with the settings as they should be, could this give a hint: ![image](https://user-images.githubusercontent.com/6975276/142232135-350efe4e-1c17-471e-a382-4c63d660017c.png)
> 
> Obviously it's related to authentication, but I can't tell the reason looking at this screenshot (though it help with the context).
> 
> What happens when you try to the following cases (replacing the relevant variables)? from a) a shell on openhabian and b) a machine in the same network as openhabian (your own pc for example)
> 
> 1. `curl -XGET http://openhabian-ip-or-domain-name/rest/items` --> I expect a 200 in both cases
> 2. `curl -XGET --header 'Authorization: Bearer OAUTHTOKEN_HERE' http://openhabian-ip-or-domain-name/rest/items` --> I also expect a 200 in both cases
> 
> ^ If 1. works, this would prove that basic authentication is probably not interfering. Also, if 2. works, it would prove that the oauth token is correct and enabled.

![image](https://user-images.githubusercontent.com/6975276/142245698-c8e9bebe-e2e8-4de4-a4f2-2c259f89bed2.png)
 the return of both is equal and just lists all my devices and their state :)

**Comment by jeroenhendricksen** [comment]
> > > Ok thx for the reply, so basicly my 'settings' seem to align with the settings as they should be, could this give a hint: ![image](https://user-images.githubusercontent.com/6975276/142232135-350efe4e-1c17-471e-a382-4c63d660017c.png)
> > 
> > 
> > Obviously it's related to authentication, but I can't tell the reason looking at this screenshot (though it help with the context).
> > What happens when you try to the following cases (replacing the relevant variables)? from a) a shell on openhabian and b) a machine in the same network as openhabian (your own pc for example)
> > 
> > 1. `curl -XGET http://openhabian-ip-or-domain-name/rest/items` --> I expect a 200 in both cases
> > 2. `curl -XGET --header 'Authorization: Bearer OAUTHTOKEN_HERE' http://openhabian-ip-or-domain-name/rest/items` --> I also expect a 200 in both cases
> > 
> > ^ If 1. works, this would prove that basic authentication is probably not interfering. Also, if 2. works, it would prove that the oauth token is correct and enabled.
> 
> ![image](https://user-images.githubusercontent.com/6975276/142245698-c8e9bebe-e2e8-4de4-a4f2-2c259f89bed2.png) the return of both is equal and just lists all my devices and their state :)
> 
> in openhabian nginx is not setup yet (i can activate it trough the openhabian-config, but it isn't enabled atm)
> 
> -> I've also updated all my packages etc now the debug log from nodered remains empty at the moment, but still can't pick an item unfortunatly. when I 'edit' the token to a wrong one then the errors reappear and also stay regardless of changing it back the the previous one :) -> untill i reboot node red than the 'error' is gone again if a correct token is entered
> 
> Update: I also ran the curls you mentioned on the server running nodered with the same result, I changed a few letters in the token to test that to, and when to token is incorrect i also get an error.

I'm trying to figure out what seems to be the problem here. You are running the latest version (1.3.26) of the `node-red-contrib-openhab3` right? The curl requests prove that simple requests work (with and without the token). 
To receive events (changes in item and group states) openhab provides a special endpoint to which I setup a connection via the 'eventsource' package, which keeps a connection open and via SSE (Server-Sent Events) receives any event directly from the server. I'm sure I've tested it with the use of an oauthv2 token, but somehow it's not working for you. I'll see if I can perform another test with my (local docker) [test setup](https://github.com/jeroenhendricksen/node-red-contrib-openhab3/blob/master/README.md#testing-the-plugin-for-development-purposes). I'm not sure what else I can do right now to get this issue fixed for you.

**Comment by jeroenvdd** [comment]
I'm using 1.3.25
but that seems to be the most recent one in the palette library:
![image](https://user-images.githubusercontent.com/6975276/142621700-30499600-c913-4267-ae48-8b8ebcf82286.png)

**Comment by jeroenhendricksen** [comment]
> I'm using 1.3.25 but that seems to be the most recent one in the palette library: ![image](https://user-images.githubusercontent.com/6975276/142621700-30499600-c913-4267-ae48-8b8ebcf82286.png)
> 
> also the webpage doesn't mention a .26 ![image](https://user-images.githubusercontent.com/6975276/142621848-19154a34-be96-49ca-97be-b0f929c5d4f0.png)

You are right. The node-red repo thinks 1.3.25 is the latest. Something went wrong updating it I guess. Not that it will help resolve your issue I'm afraid (1.3.25 should be fine though), but it's something I will look into.

**Comment by jeroenhendricksen** [comment]
I've managed to reproduce it somehow @jeroenvdd. When I add a wrong token, the connection shows a 401 after deploying immediately. When I thewn add a correct token and hit deploy, I still see a 401 appearing. Only when I restart node-red, the correct token is used and the 401 disappears (and the Server-Sent Events conenction gets set-up properly).

Have you tried restarting node-red after setting the correct token? If not, can you try? Does this help?
There is probably a bug somewhere that something is somehow cached (or something) whenever the config gets updated and deployed. But before I dive into that, I'm curious if you can get it working now.

**Comment by MDAR** [comment]
@jeroenhendricksen 

>Only when I restart node-red, the correct token is used and the 401 disappears (and the Server-Sent Events conenction gets set-up properly).

That explains a lot.

Thanks for finding that.

**Comment by jeroenvdd** [comment]
> I've managed to reproduce it somehow @jeroenvdd. When I add a wrong token, the connection shows a 401 after deploying immediately. When I thewn add a correct token and hit deploy, I still see a 401 appearing. Only when I restart node-red, the correct token is used and the 401 disappears (and the Server-Sent Events conenction gets set-up properly).
> 
> Have you tried restarting node-red after setting the correct token? If not, can you try? Does this help? There is probably a bug somewhere that something is somehow cached (or something) whenever the config gets updated and deployed. But before I dive into that, I'm curious if you can get it working now.

that is indeed the beheviour I had with the errors, after reboot it's always fine, 
but in the non error situation after a reboot, the select item field is still grey

**Comment by jeroenhendricksen** [comment]
> > I've managed to reproduce it somehow @jeroenvdd. When I add a wrong token, the connection shows a 401 after deploying immediately. When I thewn add a correct token and hit deploy, I still see a 401 appearing. Only when I restart node-red, the correct token is used and the 401 disappears (and the Server-Sent Events conenction gets set-up properly).
> > Have you tried restarting node-red after setting the correct token? If not, can you try? Does this help? There is probably a bug somewhere that something is somehow cached (or something) whenever the config gets updated and deployed. But before I dive into that, I'm curious if you can get it working now.
> 
> that is indeed the beheviour I had with the errors, after reboot it's always fine, but in the non error situation after a reboot, the select item field is still grey
> 
> I've put the login in node red to 'trace' this is my log when starting node red with only the openhab nodes configured: `21 Nov 17:48:50 - [info] Starting flows 21 Nov 17:48:50 - [debug] red/nodes/flows.start : starting flow : global 21 Nov 17:48:50 - [debug] red/nodes/flows.start : starting flow : a165db76259c0fae 21 Nov 17:48:50 - [trace] [flow:global] start flow [global] 21 Nov 17:48:50 - [trace] [flow:global] ------------------|--------------|----------------- 21 Nov 17:48:50 - [trace] [flow:global] id | type | alias 21 Nov 17:48:50 - [trace] [flow:global] ------------------|--------------|----------------- 21 Nov 17:48:50 - [trace] [flow:global] edb10d3f.60109 | server | 21 Nov 17:48:50 - [trace] [flow:global] fef53c1a1a104886 | openhab2-controller2 | 21 Nov 17:48:50 - [trace] [flow:global] ------------------|--------------|----------------- 21 Nov 17:48:50 - [trace] [flow:a165db76259c0fae] start flow [a165db76259c0fae] 21 Nov 17:48:50 - [trace] [flow:a165db76259c0fae] ------------------|--------------|----------------- 21 Nov 17:48:50 - [trace] [flow:a165db76259c0fae] id | type | alias 21 Nov 17:48:50 - [trace] [flow:a165db76259c0fae] ------------------|--------------|----------------- 21 Nov 17:48:50 - [trace] [flow:a165db76259c0fae] fbedfaba80d81830 | openhab2-monitor2 | 21 Nov 17:48:50 - [trace] [flow:a165db76259c0fae] 4012e61709b82c5f | debug | 21 Nov 17:48:50 - [trace] [flow:a165db76259c0fae] 9e0f014ca6acfc09 | openhab2-in2 | 21 Nov 17:48:50 - [trace] [flow:a165db76259c0fae] 6a90d2823724b4b8 | openhab2-out2 | 21 Nov 17:48:50 - [trace] [flow:a165db76259c0fae] 1de15e2913edd05a | openhab2-events2 | 21 Nov 17:48:50 - [trace] [flow:a165db76259c0fae] ------------------|--------------|----------------- 21 Nov 17:48:50 - [trace] runtime event: {"id":"runtime-state","retain":true} 21 Nov 17:48:50 - [info] Started flows [17:48:51] INFO: Starting NGinx... 21 Nov 17:48:51 - [trace] comms.open 2VpfMabUHRw08bUhZb16il7rghX5c7KqqT7uvFixISw= 21 Nov 17:48:52 - [info] [openhab2-controller2:Openhabian] Opened connection to http://192.168.0.195:8080/rest/events?topics=openhab/items 21 Nov 17:48:53 - [info] [openhab2-controller2:Openhabian] Connection established. Emitting 38 InitialEvents. 21 Nov 17:48:54 - [info] [openhab2-events2:1de15e2913edd05a] Opened connection to http://192.168.0.195:8080/rest/events?topics=openhab/*/*`

Good idea of you to enable tracing. I haven't been sending messages via the trace output for this module, but maybe that can be helpful, so I might add some of those.

Ok, so the Server-Sent Events work eventually (though restarting Node-RED might be required). However, retrieving the list of items does not (so it seems). A list of items are retrieved from any of the openhab2-nodes listing an item, after opening its configuration screen (by double clicking the node for example). This is done via a jquery call (`$.getJSON("/openhab2/items", config)`). When I look at the Network-tab from my (Chrome) browser' Develops console, I see its making (three!?) requests, which look like this for my test setup:
`http://localhost:1880/openhab2/items?name=openhab3-oauth2&protocol=http&host=openhab3-oauth2&port=8080&path=&username=&password=&ohversion=v3&token=oh.nodered.9hAIDUGBwtVwzefvk7SBlUF7bYNUwS9PH5bpbO7nmmAdU51fk3G7ITWeNfIBHFwGFHb2gdVTr6KdGPJq8bRw`

This also brings to mind a place where the code might collide with the [previous version of the plugin](https://github.com/pdmangel/node-red-contrib-openhab2). Are you sure you don't have this plugin installed? That might explain any interference in retrieving a list of items...
I will create a fix for that shortly...

Can you capture one of these requests and tell me the output? When I execute this request, I get a list of items, which is used by the config UI screen to populate the Items list.

**Comment by jeroenhendricksen** [comment]
I've released a new version (1.3.28) which should fix the above mentioned interference with [the previous version I forked from](https://flows.nodered.org/node/node-red-contrib-openhab2). This might help if you had that version installed alongside this module.

**Comment by jeroenvdd** [comment]
> I've released a new version (1.3.28) which should fix the above mentioned interference with [the previous version I forked from](https://flows.nodered.org/node/node-red-contrib-openhab2). This might help if you had that version installed alongside this module.

updated to this one, yet everything seems to remain.
`22 Nov 08:56:43 - [info] Starting flows
22 Nov 08:56:43 - [debug] red/nodes/flows.start : starting flow : global
22 Nov 08:56:43 - [debug] red/nodes/flows.start : starting flow : a165db76259c0fae
22 Nov 08:56:43 - [trace] [flow:global] start flow [global]
22 Nov 08:56:43 - [trace] [flow:global] ------------------|--------------|-----------------
22 Nov 08:56:43 - [trace] [flow:global]  id               | type         | alias
22 Nov 08:56:43 - [trace] [flow:global] ------------------|--------------|-----------------
22 Nov 08:56:43 - [trace] [flow:global]  edb10d3f.60109   | server       | 
22 Nov 08:56:43 - [trace] [flow:global]  fef53c1a1a104886 | openhab2-controller2 | 
22 Nov 08:56:43 - [trace] [flow:global] ------------------|--------------|-----------------
22 Nov 08:56:43 - [trace] [flow:a165db76259c0fae] start flow [a165db76259c0fae]
22 Nov 08:56:43 - [trace] [flow:a165db76259c0fae] ------------------|--------------|-----------------
22 Nov 08:56:43 - [trace] [flow:a165db76259c0fae]  id               | type         | alias
22 Nov 08:56:43 - [trace] [flow:a165db76259c0fae] ------------------|--------------|-----------------
22 Nov 08:56:43 - [trace] [flow:a165db76259c0fae]  4012e61709b82c5f | debug        | 
22 Nov 08:56:43 - [trace] [flow:a165db76259c0fae]  92bd5605d80d4052 | openhab2-in2 | 
22 Nov 08:56:43 - [trace] [flow:a165db76259c0fae] ------------------|--------------|-----------------
22 Nov 08:56:43 - [trace] runtime event: {"id":"runtime-state","retain":true}
22 Nov 08:56:43 - [info] Started flows
22 Nov 08:56:43 - [trace] runtime event: {"id":"runtime-deploy","payload":{"revision":"40d0809aee04329e87a52ad619427a5e"},"retain":true}
22 Nov 08:56:46 - [info] [openhab2-controller2:Openhabians] Opened connection to http://192.168.0.195:8080/rest/events?topics=openhab/items
22 Nov 08:56:46 - [info] [openhab2-controller2:Openhabians] Connection established. Emitting 38 InitialEvents.`

![image](https://user-images.githubusercontent.com/6975276/142824411-d32ef3ec-72e0-49dd-b20b-4063cea32fd2.png)
